ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.asadaws2026.online
CATALOGUE_HOST: catalogue-dev.asadaws2026.online
REDIS_HOST: redis-dev.asadaws2026.online
USER_HOST: user-dev.asadaws2026.online
CART_HOST: cart-dev.asadaws2026.online
MYSQL_HOST: mysql-dev.asadaws2026.online
SHIPPING_HOST: shipping-dev.asadaws2026.online
RABBITMQ_HOST: rabbitmq-dev.asadaws2026.online
PAYMENT_HOST: payment-dev.asadaws2026.online
