# $ANSIBLE_VAULT;1.1;AES256
# 31303463346162323731326139363436346464636432323266633462366534313539383333366635
# 3234623634333534393562316532656461306435623064330a613933316539663664333762616465
# 33383431346362613236336239383562373030346561383861333634653731663436643039303633
# 3162323739393561340a393136373964393033373539643330666432663965306433396137326563
# 34646235393138616133353535363662383062616661396462326465353965653834623331336534
# 6232643564373862663265303861663337383537333039363537

MYSQL_ROOT_PASSWORD: "{{ lookup('amazon.aws.ssm_parameter', '/roboshop/dev/mysql_root_password', region='us-east-1', decrypt=True) }}"