- name: call import common roles
  tags:
  - execute
  ansible.builtin.import_role:
    name: common
    tasks_from: include-vs-import.yaml
  when: os == "Redhat"
  
- name: call include common roles
  tags:
  - execute
  ansible.builtin.include_role:
    name: common
    tasks_from: include-vs-import.yaml
  when: os == "debian"
