- name: call import common roles
  ansible.builtin.import_role:
    name: common
    tasks_from: include-vs-import.yaml
  when: os == "Redhat"
  loop:
  - one
  - two
  
- name: call include common roles
  ansible.builtin.include_role:
    name: common
    tasks_from: include-vs-import.yaml
  when: os == "debian"
  loop:
  - one
  - two