- name: call import common roles
  ansible.builtin.import_role:
    name: common
    tasks_from: include-vs-import.yaml
  
- name: call include common roles
  ansible.builtin.include_role:
    name: common
    tasks_from: include-vs-import.yaml