- name: configure mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: present
 
  - name: enable and start service
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes
  
  - name: update mysql root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}
