- name: message1
  ansible.builtin.debug:
    msg: "Hi from message 1"

- name: set os to debian
  ansible.builtin.set_fact:
    os: "debian"

- name: message2
  tags:
    - execute
  ansible.builtin.debug:
    msg: "Hi from message 2"

- name: message3
  ansible.builtin.debug:
    msg: "Hi from message 3"