- name: message1
  ansible.builtin.debug:
    msg: "Hi from message 1"

- name: message2
  ansible.builtin.debug:
    msg: "Hi from message 2"

- name: message3
  ansible.builtin.debug:
    msg: "Hi from message 3"